USE exam_system;

-- 插入预存资源
INSERT INTO generated_resource (path_node_id, resource_type, title, content_json, difficulty, created_at) VALUES
(0, 'document', 'Java简介', '{"content":"# Java简介与环境设置\n\n## 什么是Java\nJava是一门面向对象的编程语言，由Sun Microsystems于1995年发布。Java具有跨平台、安全性高、简单易学等特点。\n\n## Java特点\n1. **跨平台**：一次编写，到处运行\n2. **面向对象**：封装、继承、多态\n3. **安全性高**：自动内存管理\n4. **简单易学**：语法类似C++\n\n## 环境搭建\n1. 下载JDK（Java Development Kit）\n2. 配置环境变量JAVA_HOME\n3. 安装IDE（推荐IntelliJ IDEA）\n\n## 第一个程序\n```java\npublic class Hello {\n    public static void main(String[] args) {\n        System.out.println(\"Hello World\");\n    }\n}\n```"}', 'L1', NOW()),

(0, 'quiz', 'Java简介', '{"questions":[{"content":"Java程序的入口方法是什么？","type":"CHOICE","difficulty":"EASY","options":[{"content":"main()","isCorrect":true},{"content":"start()","isCorrect":false},{"content":"run()","isCorrect":false},{"content":"init()","isCorrect":false}],"analysis":"Java程序的入口是main方法，格式为public static void main(String[] args)"},{"content":"Java是哪个公司开发的？","type":"CHOICE","difficulty":"EASY","options":[{"content":"Microsoft","isCorrect":false},{"content":"Sun Microsystems","isCorrect":true},{"content":"Google","isCorrect":false},{"content":"Oracle","isCorrect":false}],"analysis":"Java由Sun Microsystems于1995年发布，后被Oracle收购"},{"content":"Java的主要特点不包括？","type":"CHOICE","difficulty":"EASY","options":[{"content":"跨平台","isCorrect":false},{"content":"面向对象","isCorrect":false},{"content":"直接操作内存","isCorrect":true},{"content":"安全性高","isCorrect":false}],"analysis":"Java有自动内存管理，不直接操作内存"}]}', 'L1', NOW()),

(0, 'mindmap', 'Java简介', '{"topic":"Java简介","children":[{"topic":"Java历史","children":[{"topic":"1995年Sun公司发布"},{"topic":"2010年Oracle收购"}]},{"topic":"Java特点","children":[{"topic":"跨平台"},{"topic":"面向对象"},{"topic":"安全性高"},{"topic":"简单易学"}]},{"topic":"环境搭建","children":[{"topic":"下载JDK"},{"topic":"配置环境变量"},{"topic":"安装IDE"}]}]}', 'L1', NOW()),

(0, 'document', '变量与数据类型', '{"content":"# 变量与数据类型\n\n## 变量\n变量是存储数据的容器，必须先声明后使用。\n\n## 基本数据类型\n| 类型 | 大小 | 示例 |\n|------|------|------|\n| int | 4字节 | int age = 20; |\n| double | 8字节 | double price = 9.99; |\n| char | 2字节 | char grade = A; |\n| boolean | 1字节 | boolean isTrue = true; |\n\n## 引用数据类型\n- String：字符串\n- Array：数组\n- Class：类\n\n## 变量命名规则\n1. 以字母、下划线或$开头\n2. 不能使用关键字\n3. 驼峰命名法"}', 'L1', NOW()),

(0, 'quiz', '变量与数据类型', '{"questions":[{"content":"以下哪个是合法的变量名？","type":"CHOICE","difficulty":"EASY","options":[{"content":"123abc","isCorrect":false},{"content":"_name","isCorrect":true},{"content":"class","isCorrect":false},{"content":"my-var","isCorrect":false}],"analysis":"变量名不能以数字开头，不能使用关键字，不能包含连字符"},{"content":"int类型占多少字节？","type":"CHOICE","difficulty":"EASY","options":[{"content":"2字节","isCorrect":false},{"content":"4字节","isCorrect":true},{"content":"8字节","isCorrect":false},{"content":"16字节","isCorrect":false}],"analysis":"int是32位整数，占4字节"},{"content":"以下哪个不是基本数据类型？","type":"CHOICE","difficulty":"EASY","options":[{"content":"int","isCorrect":false},{"content":"boolean","isCorrect":false},{"content":"String","isCorrect":true},{"content":"char","isCorrect":false}],"analysis":"String是引用类型，不是基本数据类型"}]}', 'L1', NOW()),

(0, 'mindmap', '变量与数据类型', '{"topic":"变量与数据类型","children":[{"topic":"基本数据类型","children":[{"topic":"整数：byte/short/int/long"},{"topic":"浮点：float/double"},{"topic":"字符：char"},{"topic":"布尔：boolean"}]},{"topic":"引用数据类型","children":[{"topic":"String"},{"topic":"Array"},{"topic":"Class"}]},{"topic":"变量规则","children":[{"topic":"先声明后使用"},{"topic":"命名规范"},{"topic":"作用域"}]}]}', 'L1', NOW()),

(0, 'document', '运算符与表达式', '{"content":"# 运算符与表达式\n\n## 算术运算符\n- +：加法\n- -：减法\n- *：乘法\n- /：除法\n- %：取模\n\n## 比较运算符\n- ==：等于\n- !=：不等于\n- >：大于\n- <：小于\n- >=：大于等于\n- <=：小于等于\n\n## 逻辑运算符\n- &&：与\n- ||：或\n- !：非\n\n## 赋值运算符\n- =：赋值\n- +=：加等于\n- -=：减等于"}', 'L1', NOW()),

(0, 'quiz', '运算符与表达式', '{"questions":[{"content":"5 % 2 的结果是？","type":"CHOICE","difficulty":"EASY","options":[{"content":"2","isCorrect":false},{"content":"2.5","isCorrect":false},{"content":"1","isCorrect":true},{"content":"0","isCorrect":false}],"analysis":"%是取模运算，5除以2余1"},{"content":"true && false 的结果是？","type":"CHOICE","difficulty":"EASY","options":[{"content":"true","isCorrect":false},{"content":"false","isCorrect":true},{"content":"null","isCorrect":false},{"content":"编译错误","isCorrect":false}],"analysis":"&&是与运算，两个都为true才为true"},{"content":"以下哪个不是Java运算符？","type":"CHOICE","difficulty":"EASY","options":[{"content":"+=","isCorrect":false},{"content":"&&","isCorrect":false},{"content":"**","isCorrect":true},{"content":"!=","isCorrect":false}],"analysis":"**不是Java运算符，幂运算用Math.pow()"}]}', 'L1', NOW()),

(0, 'mindmap', '运算符与表达式', '{"topic":"运算符与表达式","children":[{"topic":"算术运算符","children":[{"topic":"+ - * / %"}]},{"topic":"比较运算符","children":[{"topic":"== != > < >= <="}]},{"topic":"逻辑运算符","children":[{"topic":"&& || !"}]},{"topic":"赋值运算符","children":[{"topic":"= += -= *= /="}]}]}', 'L1', NOW()),

(0, 'document', '控制流', '{"content":"# 控制流\n\n## 条件语句\n### if-else\n```java\nif (score >= 90) {\n    System.out.println(\"优秀\");\n} else if (score >= 60) {\n    System.out.println(\"及格\");\n} else {\n    System.out.println(\"不及格\");\n}\n```\n\n### switch\n```java\nswitch (day) {\n    case 1: System.out.println(\"周一\"); break;\n    case 2: System.out.println(\"周二\"); break;\n    default: System.out.println(\"其他\");\n}\n```\n\n## 循环语句\n### for循环\n```java\nfor (int i = 0; i < 10; i++) {\n    System.out.println(i);\n}\n```\n\n### while循环\n```java\nwhile (condition) {\n    // 循环体\n}\n```"}', 'L1', NOW()),

(0, 'quiz', '控制流', '{"questions":[{"content":"for循环的执行顺序是？","type":"CHOICE","difficulty":"EASY","options":[{"content":"初始化-判断-执行-更新","isCorrect":true},{"content":"判断-初始化-执行-更新","isCorrect":false},{"content":"执行-判断-更新-初始化","isCorrect":false},{"content":"初始化-执行-判断-更新","isCorrect":false}],"analysis":"for循环先初始化，再判断，然后执行循环体，最后更新"},{"content":"以下哪个不是循环语句？","type":"CHOICE","difficulty":"EASY","options":[{"content":"for","isCorrect":false},{"content":"while","isCorrect":false},{"content":"switch","isCorrect":true},{"content":"do-while","isCorrect":false}],"analysis":"switch是条件语句，不是循环语句"},{"content":"break的作用是？","type":"CHOICE","difficulty":"EASY","options":[{"content":"继续循环","isCorrect":false},{"content":"跳出当前循环","isCorrect":true},{"content":"跳过本次循环","isCorrect":false},{"content":"结束程序","isCorrect":false}],"analysis":"break用于跳出当前循环"}]}', 'L1', NOW()),

(0, 'mindmap', '控制流', '{"topic":"控制流","children":[{"topic":"条件语句","children":[{"topic":"if-else"},{"topic":"switch-case"}]},{"topic":"循环语句","children":[{"topic":"for循环"},{"topic":"while循环"},{"topic":"do-while循环"}]},{"topic":"跳转语句","children":[{"topic":"break"},{"topic":"continue"}]}]}', 'L1', NOW()),

(0, 'document', '方法', '{"content":"# 方法（函数）\n\n## 方法定义\n```java\npublic static int add(int a, int b) {\n    return a + b;\n}\n```\n\n## 方法调用\n```java\nint result = add(3, 5);\nSystem.out.println(result); // 8\n```\n\n## 参数传递\n- 值传递：基本类型\n- 引用传递：引用类型\n\n## 方法重载\n同一个类中，方法名相同，参数列表不同\n```java\npublic static int add(int a, int b) { ... }\npublic static double add(double a, double b) { ... }\n```"}', 'L1', NOW()),

(0, 'quiz', '方法', '{"questions":[{"content":"方法重载的条件是？","type":"CHOICE","difficulty":"EASY","options":[{"content":"方法名相同，参数列表不同","isCorrect":true},{"content":"方法名不同","isCorrect":false},{"content":"返回值不同","isCorrect":false},{"content":"访问修饰符不同","isCorrect":false}],"analysis":"方法重载要求方法名相同，参数列表不同（类型、个数、顺序）"},{"content":"以下哪个是合法的方法定义？","type":"CHOICE","difficulty":"EASY","options":[{"content":"public void 1method() {}","isCorrect":false},{"content":"public void method() {}","isCorrect":true},{"content":"public void method-2() {}","isCorrect":false},{"content":"public void method int() {}","isCorrect":false}],"analysis":"方法名不能以数字开头，不能包含连字符"},{"content":"return语句的作用是？","type":"CHOICE","difficulty":"EASY","options":[{"content":"继续执行","isCorrect":false},{"content":"返回值并结束方法","isCorrect":true},{"content":"跳过本次循环","isCorrect":false},{"content":"抛出异常","isCorrect":false}],"analysis":"return用于返回值并结束方法执行"}]}', 'L1', NOW()),

(0, 'mindmap', '方法', '{"topic":"方法","children":[{"topic":"方法定义","children":[{"topic":"访问修饰符"},{"topic":"返回类型"},{"topic":"方法名"},{"topic":"参数列表"},{"topic":"方法体"}]},{"topic":"方法调用","children":[{"topic":"实参传递"},{"topic":"返回值接收"}]},{"topic":"方法重载","children":[{"topic":"方法名相同"},{"topic":"参数列表不同"}]}]}', 'L1', NOW()),

(0, 'document', '数组', '{"content":"# 数组\n\n## 数组定义\n```java\nint[] arr = new int[5];\nint[] arr2 = {1, 2, 3, 4, 5};\n```\n\n## 数组访问\n```java\nint first = arr[0]; // 获取第一个元素\narr[1] = 10; // 设置第二个元素\n```\n\n## 数组长度\n```java\nint len = arr.length;\n```\n\n## 遍历数组\n```java\nfor (int i = 0; i < arr.length; i++) {\n    System.out.println(arr[i]);\n}\n\nfor (int num : arr) {\n    System.out.println(num);\n}\n```"}', 'L1', NOW()),

(0, 'quiz', '数组', '{"questions":[{"content":"数组下标从几开始？","type":"CHOICE","difficulty":"EASY","options":[{"content":"1","isCorrect":false},{"content":"0","isCorrect":true},{"content":"-1","isCorrect":false},{"content":"任意","isCorrect":false}],"analysis":"Java数组下标从0开始"},{"content":"获取数组长度用什么？","type":"CHOICE","difficulty":"EASY","options":[{"content":"arr.size()","isCorrect":false},{"content":"arr.length()","isCorrect":false},{"content":"arr.length","isCorrect":true},{"content":"arr.count()","isCorrect":false}],"analysis":"数组长度用arr.length属性，不是方法"},{"content":"访问不存在的数组下标会？","type":"CHOICE","difficulty":"EASY","options":[{"content":"返回null","isCorrect":false},{"content":"返回0","isCorrect":false},{"content":"抛出异常","isCorrect":true},{"content":"自动扩容","isCorrect":false}],"analysis":"访问不存在的下标会抛出ArrayIndexOutOfBoundsException"}]}', 'L1', NOW()),

(0, 'mindmap', '数组', '{"topic":"数组","children":[{"topic":"数组定义","children":[{"topic":"动态初始化"},{"topic":"静态初始化"}]},{"topic":"数组操作","children":[{"topic":"访问元素"},{"topic":"修改元素"},{"topic":"获取长度"}]},{"topic":"数组遍历","children":[{"topic":"for循环"},{"topic":"for-each循环"}]}]}', 'L1', NOW()),

(0, 'document', '面向对象编程基础', '{"content":"# 面向对象编程基础\n\n## 类和对象\n```java\nclass Student {\n    String name;\n    int age;\n    \n    void study() {\n        System.out.println(name + \"在学习\");\n    }\n}\n\nStudent s = new Student();\ns.name = \"张三\";\ns.study();\n```\n\n## 三大特性\n1. **封装**：隐藏内部实现\n2. **继承**：代码复用\n3. **多态**：同一行为不同表现\n\n## 构造方法\n```java\nclass Student {\n    String name;\n    \n    Student(String name) {\n        this.name = name;\n    }\n}\n```"}', 'L1', NOW()),

(0, 'quiz', '面向对象编程基础', '{"questions":[{"content":"面向对象的三大特性是？","type":"CHOICE","difficulty":"EASY","options":[{"content":"封装、继承、多态","isCorrect":true},{"content":"封装、继承、重载","isCorrect":false},{"content":"抽象、继承、多态","isCorrect":false},{"content":"封装、重写、多态","isCorrect":false}],"analysis":"面向对象三大特性是封装、继承、多态"},{"content":"构造方法的作用是？","type":"CHOICE","difficulty":"EASY","options":[{"content":"定义方法","isCorrect":false},{"content":"创建对象时初始化","isCorrect":true},{"content":"销毁对象","isCorrect":false},{"content":"继承父类","isCorrect":false}],"analysis":"构造方法用于创建对象时初始化"},{"content":"this关键字的作用是？","type":"CHOICE","difficulty":"EASY","options":[{"content":"引用当前对象","isCorrect":true},{"content":"引用父类","isCorrect":false},{"content":"引用子类","isCorrect":false},{"content":"引用静态方法","isCorrect":false}],"analysis":"this引用当前对象的属性和方法"}]}', 'L1', NOW()),

(0, 'mindmap', '面向对象编程基础', '{"topic":"面向对象编程","children":[{"topic":"类和对象","children":[{"topic":"类的定义"},{"topic":"对象创建"},{"topic":"成员变量和方法"}]},{"topic":"三大特性","children":[{"topic":"封装"},{"topic":"继承"},{"topic":"多态"}]},{"topic":"构造方法","children":[{"topic":"无参构造"},{"topic":"有参构造"},{"topic":"this关键字"}]}]}', 'L1', NOW());
